### ISSUE TITLE
Publish on Homebrew

### ISSUE THREAD

**Issue by sdavids** [adoble/adr-j#23]
It would be nice if one could install _adr-j_ via homebrew.

Similar to the existing `brew install adr-tools`.

**Comment by adoble** [comment]
I agree that the existing install procedure is a little kludgy. To have a simpler installation method would be better. 

In the context of [ADR 2](https://github.com/adoble/adr-j/blob/master/doc/adr/0002-implement-as-Java.md),  one of the goals was that the tool could be used “on a wide variety of operating systems.”. Ideally, I would like to use one installation mechanism for all systems. To the best of my knowledge, homebrew only works for macOS and Linux. If one exists that can handle all (including Windows) then I would go for that. 

However, I don’t know if such a tool exists (or even if it is possible). Have you (or anyone else) any ideas? Or do we have to go with a variety of OS specific installation tools?

**Comment by sdavids** [comment]
Unfortunately, there is no single one for all platforms and each platform has lots of alternatives.

As far as I see it, the following are the most used and support for them would make Pareto happy 😉

Mac:

  https://brew.sh

Windows:

  https://chocolatey.org

Linux:

  https://help.launchpad.net/Packaging/PPA

**Comment by danielspangler** [comment]
@sdavids  FWIW, I created one here: https://github.com/danielspangler/homebrew-playground.  I'm not an expert on Homebrew formulas but it seems to work if I tap that repository.  I did end up ignoring the built in Gradle wrapper because it doesn't work with the latest Java SDK.  I'm calling Gradle directly and setting it up as a dependency in the Formula.

**Comment by adoble** [comment]
@danielspangler Thanks for this. 

Unfortunately I don’t have access to a Mac, so I tried the Homebrew formula out on a linux virtual machine (GCP). (Not surprisingly) it worked a treat. 

Now I could just copy the code over to the project, but would much prefer a PR - in this way the attribution trace stays recorded. How do you want to play it? 

I’m planning a major release and could then package this up with it, but as my [comment ](https://github.com/adoble/adr-j/issues/32#issuecomment-609072518) for Issue 32 indicates, this may take some time.

**Comment by adoble** [comment]
Coming back to this after some considerable time. As of version 3.2.3 `adr-j`, is using [`jbang`](https://www.jbang.dev/) for the installation as this seems to be OS independent.

Closing this  issue.
