### ISSUE TITLE
Use ISO_LOCAL_DATE format

### ISSUE THREAD

**Issue by sdavids** [adoble/adr-j#28]
Using the default locale for date formatting is not good in an international team.

Related:
https://github.com/GingerTommy/adr-cli/blob/master/docs/adr/0002-use-iso-8601-date-format.md

**Comment by sdavids** [comment]
#27

**Comment by adoble** [comment]
Merged PR#27 in. 

Perhaps should also consider being able to change the date format with the planned config command https://github.com/adoble/adr-j/issues/13
