### ISSUE TITLE
consider providing jbang catalog for easy usage

### ISSUE THREAD

**Issue by maxandersen** [adoble/adr-j#44]
if you had a [jbang-catalog](https://www.jbang.dev/documentation/guide/latest/alias_catalogs.html#catalogs) defined we could do:

`jbang app install adr@adoble` and have it available as `adr` on any platform supporting java.

I didn't find adr jar published anywhere but by using jitpack you can mimck it:

`jbang app install --name adr --repos jitpack -m org.doble.adr.ADR com.github.adoble:adr-j:LATEST`

now you can run`adr`

I'll open PR with example catalog if you are interested. best would be if you created adoble/jbang-catalog repo then the name would just be adr@adoble rather than adr@adoble/adr-j

**Comment by adoble** [comment]
When I first started this project, finding a platform independent mechanism to install a java program was challenging.

I haven't been working in the Java ecosystem for some time now, so I'm pleased to see that things have progressed. Thanks for the hint and the offer of a PR. I'd be very interested to get a smooth  installation going with `jbang`, but won't be able to start on it just now.

**Comment by adoble** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Issue 44 - JBang](https://trello.com/c/h2r7Pr9J/104-issue-44-jbang)

**Comment by adoble** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Close Issue 26](https://trello.com/c/3cQPf4By/113-close-issue-26)

**Comment by adoble** [comment]
Took me sometime, but I've have done what you suggested and set up a [`jbang-catalog`](https://github.com/adoble/jbang-catalog) repo as well as  updated the installation instructions to show how `jbang` is used. ADR-J can now be installed with:

```
 jbang app install adr@adoble
```


I was impressed at how easy this made the installation, so thanks for this. 

I'll close the issue now.
