### ISSUE TITLE
Add documentation for the adr.properties file

### ISSUE THREAD

**Issue by sdavids** [adoble/adr-j#46]
It should be mentioned somewhere and the options should be explained.

Currently, it is only implicitly it is described by [adr config](https://github.com/adoble/adr-j/blob/main/doc/man/config.md).

**Comment by adoble** [comment]
Added a link in the README  file to a brief description of the `adr.properties` file.

**Comment by adoble** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Issue 46](https://trello.com/c/eQk1w8Wm/101-issue-46)
