### ISSUE TITLE
Provide template variables for year and author_email

### ISSUE THREAD

**Issue by sdavids** [adoble/adr-j#49]
Use case:

template.md
```markdown
<!--
SPDX-FileCopyrightText: © {{year}} {{author}} <{{author_email}}>
SPDX-License-Identifier: Apache-2.0
-->
# {{id}}. {{name}}

Status: {{status}}
Date: {{date}}
```

## More information

[REUSE - Add copyright and licensing information to each file](https://reuse.software/faq/#step-2)

**Comment by sdavids** [comment]
An alternative would be to add a pipe to the existing `date` variable.

Similar to [Angular - DatePipe](https://angular.io/api/common/DatePipe)

Usage would be:

`{{date}}`
`{{date|YEAR}}`
`{{date|ISO_OFFSET_DATE}}`
`{{date|LONG}}`

This line would have to be changed:

```java
.map(line -> line.replaceAll("\\{\\{date\\}\\}", dateFormatter.format(date)))
```

Supported would be all options from [DateFormatEnum](https://github.com/adoble/adr-j/blob/ccb3bc92266a0f114a1cedbc09a1a506d724b2a8/src/main/java/org/doble/adr/DateFormatEnum.java) and a new option `YEAR` would be added (maybe also other from `java.time.temporal.ChronoField`).

`{{date}}` would keep the existing behavior.

**Comment by adoble** [comment]
Instead of just adding these variable, I would prefer to see a mechanism in which template writers can also add new variables as they see fit. 

One approach would be that a template writer design a template with known and new variables (rather like you did). Then during initialization an ADR can update these with a value, something like:

```console
> adr init -t template.md 
> adr variables  add email adrwriter@bigcorp.com
> adr variables  add company BigCorp
```

and then these would be merged in to the ADRs.

These provides more flexibility (although I think the ergonomics could be improved). 

Dynamic variables such as date are more difficult, but could use the approach you suggested.

**Comment by adoble** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Issue 49 - Provide template variables for year and author_email](https://trello.com/c/4apZV8Xp/127-issue-49-provide-template-variables-for-year-and-authoremail)

**Comment by sdavids** [comment]
> I would prefer to see a mechanism in which template writers can also add new variables as they see fit.

I understand and second your suggestion.

I am unsure of where on the scale simplicity—configurability you want to take this project.

I am unsure of re-inventing another template engine or embedding an existing one.

You might want to take a look at:

[Creating a Template Processor](https://docs.oracle.com/en/java/javase/21/language/string-templates.html#GUID-77EBAC35-186C-42D4-A1CA-9145DB669ACC)

One would have to use `java --release 21 --enable-preview -jar adr….jar` in that case though.

**Comment by sdavids** [comment]
And existent templates would not be compatible:

`{{date}}`

⇓

`\{date}`

**Comment by sdavids** [comment]
I could author the `YEAR` option while you decide on which way to continue?

**Comment by adoble** [comment]
Thanks for the offer. If you could author the `YEAR` option , that would be great.

I think that "hard coding" these for the time being would be the practical way forward.  

I also am concerned that the project ends up developing a complete templating engine. There is also the fact that the usual templating approach loses semantic information (see issue #47).  Using on-board material such as Java string templates is maybe a way forward, but as you pointed out, it's not as easy once you look deeper.

**Comment by sdavids** [comment]
#52

**Comment by adoble** [comment]
Thanks for the PRs to include these features. I have made a new release 3.3.0 with these in.
