### ISSUE TITLE
Command list does not always sort the entries correctly

### ISSUE THREAD

**Issue by adoble** [adoble/adr-j#54]
As noticed [here](https://github.com/adoble/adr-j/pull/53#issue-2402023475) `adr list` does not always sort the entries correctly although a sort is explicity called in the code (see `CommandList.java`)

**Comment by sdavids** [comment]
Verified on macOS: 

```shell
$ adr version
Version 3.2.3
$ mkdir /tmp/test && cd "$_"
$ adr init
Creating ADR directory at /private/tmp/test/doc/adr
$ adr new a
Creating ADR
Created ADR at /private/tmp/test/doc/adr/0002-a.md
Opening Editor on /private/tmp/test/doc/adr/0002-a.md ...
/private/tmp/test/doc/adr/0002-a.md
$ adr new b
Creating ADR
Created ADR at /private/tmp/test/doc/adr/0003-b.md
Opening Editor on /private/tmp/test/doc/adr/0003-b.md ...
$ adr new c
Creating ADR
Created ADR at /private/tmp/test/doc/adr/0004-c.md
Opening Editor on /private/tmp/test/doc/adr/0004-c.md ...
/private/tmp/test/doc/adr/0004-c.md
$ adr list
0001-record-architecture-decisions.md
0002-a.md
0004-c.md
0003-b.md
```

**Comment by sdavids** [comment]
```shell
$ jshell --feedback=silent -  <<< 'Files.list(Path.of("doc", "adr")).forEachOrdered(System.out::println)'
doc/adr/0001-record-architecture-decisions.md
doc/adr/0002-a.md
doc/adr/0004-c.md
doc/adr/0003-b.md
$ jshell --feedback=silent -  <<< 'Files.list(Path.of("doc", "adr")).map(Path::getFileName).forEachOrdered(System.out::println)'
0001-record-architecture-decisions.md
0002-a.md
0004-c.md
0003-b.md
$ jshell --feedback=silent - <<< 'Files.list(Path.of("doc", "adr")).map(Path::getFileName).sorted().forEach(System.out::println)'
0001-record-architecture-decisions.md
0002-a.md
0003-b.md
0004-c.md
```

`forEachOrdered` does not sort use `sorted` instead.

https://docs.oracle.com/en/java/javase/21/docs/api/java.base/java/util/stream/Stream.html#forEachOrdered(java.util.function.Consumer)

https://docs.oracle.com/en/java/javase/21/docs/api/java.base/java/util/stream/Stream.html#sorted()

**Comment by sdavids** [comment]
https://github.com/google/jimfs/issues/362

**Comment by adoble** [comment]
Thanks for figuring this out. I'll change the code to use `sorted`.

**Comment by adoble** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Issue 54](https://trello.com/c/QxpD9Vix/141-issue-54)

**Comment by adoble** [comment]
I've changed to code as suggested and pushed it to the main branch. Still not released as yet.

**Comment by sdavids** [comment]
Reviewed the code but have not verified runtime behavior—hope to have time this weekend.

**Comment by adoble** [comment]
Kein Stress

**Comment by sdavids** [comment]
Verified 9a2e0a2 with macOS 12.7.6.

**Comment by adoble** [comment]
Thanks. I'm closing the issue.
