### ISSUE TITLE
Gradle 8.2 is not compatible with Java 21

### ISSUE THREAD

**Issue by sdavids** [adoble/adr-j#55]
https://docs.gradle.org/8.4/release-notes.html#java-21

> Java 21 is now supported for compiling, testing, and running such projects.

https://docs.gradle.org/8.5/release-notes.html#java-21

> Gradle now supports running on Java 21.

[Update compatability to java 21](https://github.com/adoble/adr-j/commit/3e3ce86992afaf815e3b0ac2129cd9d2e50bea83)

https://github.com/adoble/adr-j/blob/0e9f390e20453ac7cf9ddff797c73e1d5985056e/gradle/wrapper/gradle-wrapper.properties#L3

https://github.com/adoble/adr-j/blob/0e9f390e20453ac7cf9ddff797c73e1d5985056e/build.gradle#L16-L17

**Comment by sdavids** [comment]
Current version is [8.10](https://docs.gradle.org/8.10/release-notes.html).

If you want to migrate to Kotlin-DSL: I could help with that.

**Comment by adoble** [comment]
Kotlin-DSL does seem to be the better alternative. If you could help with the migration that would be great.

**Comment by sdavids** [comment]
#56
