### ISSUE TITLE
Backwards compatablity

### ISSUE THREAD

**Issue by adoble** [adoble/adr-j#58]
I am concerned that supporting backwards compatibility right back to Java 8 ([see PR 53](https://github.com/adoble/adr-j/pull/53)) will result in problems down the line (e.g. new functionality that uses other libraries, inability to use new features in Java that could lighten the coding workload). This was the reason for [ADR 8](https://github.com/adoble/adr-j/blob/main/doc/adr/0008-use-java-lts-versions.md).

However, as @wviana [mentioned](https://github.com/adoble/adr-j/pull/53#issuecomment-2223940992)
   

> Big enterprise projects using ADRs are probably not on the cutting edge java version.

So my proposal would be:

 *   Use the the latest Java LTS version for development (as per ADR 8)
  *  Provide backwards compatibly for two LTS versions before (e.g developed using Java 21, compatible with Java 11 - exactly as was done in[ PR 57](https://github.com/adoble/adr-j/pull/57))
  *  The old compatibility version is signaled as being deprecated. In our current case this means that version 11 is shown as deprecated
  *  Supersede [ADR 8](https://github.com/adoble/adr-j/blob/main/doc/adr/0008-use-java-lts-versions.md) to show this change.

Any thoughts on this?

**Comment by sdavids** [comment]
See comments in https://github.com/adoble/adr-j/commit/07e8a69507e7e8fdd03ccb87579a3c458a335aeb.

---

I suggest:

### Gradle build

current LTS

https://github.com/adoble/adr-j/blob/07e8a69507e7e8fdd03ccb87579a3c458a335aeb/gradle/gradle-daemon-jvm.properties#L3
https://github.com/adoble/adr-j/blob/07e8a69507e7e8fdd03ccb87579a3c458a335aeb/build.gradle.kts#L25

### Sources

`src/main`: release = current LTS - 2

https://github.com/adoble/adr-j/blob/07e8a69507e7e8fdd03ccb87579a3c458a335aeb/build.gradle.kts#L41

`src/test`: release = current LTS

https://github.com/adoble/adr-j/blob/07e8a69507e7e8fdd03ccb87579a3c458a335aeb/build.gradle.kts#L25

So basically the current setup.

---

When a new LTS drops the following lines have to be changed:

https://github.com/adoble/adr-j/blob/07e8a69507e7e8fdd03ccb87579a3c458a335aeb/gradle/gradle-daemon-jvm.properties#L3
https://github.com/adoble/adr-j/blob/07e8a69507e7e8fdd03ccb87579a3c458a335aeb/build.gradle.kts#L25
https://github.com/adoble/adr-j/blob/07e8a69507e7e8fdd03ccb87579a3c458a335aeb/build.gradle.kts#L41

The major version should be increased:

https://github.com/adoble/adr-j/blob/07e8a69507e7e8fdd03ccb87579a3c458a335aeb/build.gradle.kts#L20

The changelog/release notes should say something along the lines:

> We have dropped support for Java version 11; the new minimum JRE version is 17.

**Comment by adoble** [comment]
Thanks for the review.

I've added some comments to the [build script](https://github.com/adoble/adr-j/blob/37c7bdcaf4ff707d9c14447e6b67ccb0d8180d36/build.gradle.kts) to highlight where things need to be changed and also created [ADR 10](https://github.com/adoble/adr-j/blob/37c7bdcaf4ff707d9c14447e6b67ccb0d8180d36/doc/adr/0010-binary-compatability-to-java-lts-version-minus-2.md) to cover binary compatibility.
